import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className="p-4">
            <Head>
                <title>9Hundred100Five1 / Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div id="main" className="min-h-screen p-16 flex flex-col justify-center items-top">
                    <p className="m-0 text-7xl font-medium items-top no-underline h-40 bg-gradient-to-l from-cyan-400 to-green-500 text-clip-fill">
                        <span> 910051_log</span>
                    </p>
                </div>
                <div id="skills">
                    <p></p>
                </div>

            </main>


        </div>
    )
}
